---
title: "Kubernetes Sig-Usability Survey"
author: "Carl J. Pearson"
date: "8/11/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(ggthemes)
library(ggsci)
library(scales)
theme_set(ggthemes::theme_tufte(base_family = "sans"))

df <- read_csv(here("data_cleaned.csv"))

df <- df %>%
  mutate(
    number_of_machines = factor(number_of_machines, levels=c( #properly order factors
      "1-5",
      "6-20",
      "21-50",
      "51-100",
      "101-200",
      "201-500",
      "501-1000",
      "1001-2000",
      "2001-5000",
      "5000+"
      
    ))
    
  )
```

## Sig Usability Survey

Background

## Location of respondents

```{r location,echo=F}
df %>%
  ggplot(aes(location,fill=location)) +
  geom_bar() +
  geom_text(stat='count',aes(label=..count..),vjust=-.5,size=4.5) +
  coord_cartesian(ylim=c(0,60)) +
  #labels
  #theming
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text = element_text(size=12),
    axis.title = element_blank(),
    plot.title = element_blank(),
    legend.position = "none"
    )+
  scale_x_discrete(labels = wrap_format(20)) +
  scale_fill_manual(values = rep("royalblue",50))
```


## Organization type of respondents

```{r org,echo=F}
#org type
df %>%
  ggplot(aes(org_type,fill=org_type)) +
  geom_bar() +
  geom_text(stat='count',aes(label=..count..),vjust=-.5,size=4.5) +
  coord_cartesian(ylim=c(0,80)) +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text = element_text(size=12),
    axis.title = element_blank(),
    plot.title = element_blank(),
    legend.position = "none")+
  scale_fill_manual(values = rep("royalblue",50))
```

## Job functions

```{r job,echo=F, message=F}

df %>%
  select(contains("job_function"),id) %>%
  pivot_longer(-id) %>%
  drop_na(value) %>%
  count(value) %>%
  ggplot(aes(x=reorder(value,n),y=n,fill=value)) +
  geom_bar(stat='identity') +
  geom_text(aes(label=n),hjust=-.3,size=3.5) +
  coord_cartesian(xlim=c(0,60)) +
  coord_flip() +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text = element_text(size=10),
    axis.title = element_blank(),
    plot.title = element_blank(),
    legend.position = "none") +
  scale_fill_manual(values = rep("royalblue",50))
```

## Role

```{r role,echo=F, message=F}

df %>%
  count(role) %>%
  drop_na(role) %>%
  ggplot(aes(x=reorder(role,n),y=n,fill="place")) +
  geom_bar(stat='identity') +
  geom_text(aes(label=n),hjust=-.3,size=3.5) +
  coord_cartesian(xlim=c(0,60)) +
  coord_flip() +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text = element_text(size=10),
    axis.title = element_blank(),
    legend.position = "none")+
  scale_fill_manual(values = rep("royalblue",50))

```

Other responses: Pre-Sales SE, Architect, Software Engineer

## Role by Job function

```{r role by job,echo=F, message=F}

df %>%
  select(contains("job_function"),id,role) %>%
  pivot_longer(contains("job_function")) %>%
  drop_na(value,name,role) %>%
  group_by(role) %>%
  count(value) %>%
  ggplot(aes(x=reorder(value,n),y=n,fill=role)) +
  geom_bar(stat='identity') +
#  geom_text(aes(label=n),hjust=-.3,size=3.5) +
  coord_flip() +
  theme(
    #axis.ticks.x = element_blank(),
    #axis.text.x = element_blank(),
    axis.text = element_text(size=10),
    axis.title = element_blank(),
    legend.position = c(0.8, 0.4)) +
  scale_fill_futurama() 

```

## Data center

```{r datacenter,echo=F, message=F}

df %>%
  select(contains("data_center"),id) %>%
  pivot_longer(-id) %>%
  drop_na(value) %>%
  count(value) %>%
  ggplot(aes(x=reorder(value,n),y=n,fill=value)) +
  geom_bar(stat='identity') +
  geom_text(aes(label=n),hjust=-.3,size=3.5) +
  coord_cartesian(xlim=c(0,60)) +
  coord_flip() +
  labs(title="Data center types"
  ) +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text = element_text(size=10),
    axis.title = element_blank(),
    legend.position = "none") +
  scale_fill_manual(values = rep("royalblue",50))

```

## Number of machines

```{r numberofmachines,echo=F, message=F,warning=F}

df %>%
  count(number_of_machines) %>%
  drop_na(number_of_machines) %>%
  ggplot(aes(x=number_of_machines,y=n,fill=number_of_machines)) +
  geom_bar(stat='identity') +
  geom_text(aes(label=n),hjust=-.3,size=3.5) +
  coord_cartesian(xlim=c(0,60)) +
  coord_flip() +
  labs(title="Number of machines"
  ) +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text = element_text(size=10),
    axis.title = element_blank(),
    legend.position = "none") +
  scale_fill_manual(values = rep("royalblue",50))

```


## Activities

```{r activities,echo=F, message=F}

df %>%
  select(id,contains("activities_")) %>%
  pivot_longer(contains("activities_")) %>%
  mutate(name=gsub("activities_","",name)) %>%
  drop_na(value) %>%
  group_by(name) %>%
  mutate(total=n()) %>%
  group_by(name,value,total) %>%
  count() %>%
  mutate(prop=n/total) %>%
  ggplot(aes(x=reorder(name,n),y=prop,fill=value)) +
  geom_bar(stat='identity',position = "stack") +
  coord_flip() +
  scale_fill_futurama() +
  labs(x="",y="Proportion") +
  scale_x_discrete(labels = wrap_format(30))

```

## Container adoption

```{r containers,echo=F, message=F}

df %>%
  select(id,contains("container_")) %>%
  pivot_longer(contains("container_")) %>%
  mutate(name=gsub("container_","",name)) %>%
  drop_na(value) %>%
  group_by(name) %>%
  mutate(total=n()) %>%
  ungroup() %>%
  mutate(
         value=factor(value,levels = c("Used in the past","Currently using","Future plans","N/A")),
         name=factor(name,levels = c("Proof of concept","Development","Test","Production"))
         ) %>%
  group_by(name,value,total) %>%
  count() %>%
  mutate(prop=n/total) %>%
  ggplot(aes(x=name,y=prop,fill=value)) +
  geom_bar(stat='identity',position = "dodge") +
  coord_flip() +
  scale_fill_futurama() +
  labs(x="",y="Proportion") +
  scale_x_discrete(labels = wrap_format(30))

```

## kubernetes adoption

```{r kubernetes,echo=F, message=F}

df %>%
  select(id,contains("kubernetes_")) %>%
  pivot_longer(contains("kubernetes_")) %>%
  mutate(name=gsub("kubernetes_","",name)) %>%
  drop_na(value) %>%
  group_by(name) %>%
  mutate(total=n()) %>%
  group_by(name,value,total) %>%
  count() %>%
  ungroup() %>%
  mutate(prop=n/total,
         name=factor(name,levels = c("Proof of concept","Development","Test","Production"))) %>%
  filter(name!="Other (please specify)") %>% #removed other response
  ggplot(aes(x=name,y=prop,fill=value)) +
  geom_bar(stat='identity',position = "dodge") +
  coord_flip() +
  scale_fill_futurama() +
  labs(x="",y="Proportion") 

```

## Learning sources

```{r learn,echo=F, message=F}

df %>%
  select(id,contains("learn_")) %>%
  pivot_longer(contains("learn_")) %>%
  mutate(name=gsub("learn_","",name)) %>%
  drop_na(value) %>%
  count(name) %>%
  ggplot(aes(x=name,y=n,fill="single_color")) +
  geom_bar(stat='identity') +
  geom_text(aes(label=n),hjust=-.3,size=3.5) +
  coord_flip() +
  scale_fill_futurama() +
  labs(x="",y="Proportion") +
  scale_x_discrete(labels = wrap_format(30))  +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text = element_text(size=10),
    axis.title = element_blank(),
    legend.position = "none") +
  scale_fill_manual(values = rep("royalblue",50))

```

## Learning sources: other

```{r learn2,echo=F, message=F}

df$`learn_Other (please specify)` %>% as.vector() %>% na.omit()

```

## NPS

```{r nps,echo=F, message=F, warning=F}

df_nps <- df %>%
  mutate(NPS_Categories = case_when(
    nps < 7 ~ "Detractor",
    nps == 7 | nps == 8 ~ "Passive",
    nps == 9 | nps == 10 ~ "Promoter"
  )) %>%
  drop_na(nps) %>%
  mutate(total=n()) %>%
  group_by(NPS_Categories,total) %>%
  count() %>%
  mutate(prop=n/total) %>%
  select(-total,-n) %>%
  pivot_wider(names_from = NPS_Categories,values_from = prop)

nps_value = scales::percent(df_nps$Promoter-df_nps$Detractor)


df %>%
  mutate(NPS_Categories = case_when(
    nps < 7 ~ "Detractor",
    nps == 7 | nps == 8 ~ "Passive",
    nps == 9 | nps == 10 ~ "Promoter"
  )) %>%
  ggplot(aes(nps,fill=NPS_Categories)) +
  geom_bar() +
  scale_fill_manual(values = c("#EE0000","#FFEA6C","#82C299")) +
  scale_x_continuous(breaks=seq(0,10,1), limits=c(-0.5,10.5)) +
  labs(y="Count",x="") +
  annotate("text", x = 2, y = 30, label = paste0("NPS score is ",nps_value))

```

